### ISSUE TITLE
Current release 0.5.2 doesn't work with GHE

### ISSUE THREAD

**Issue by slantview** [aktau/github-release#11]
Github Enterprise support works with master, but not with 0.5.2.  Can you please cut a new release?

**Comment by aktau** [comment]
A bit strange, as there were no commits after 0.5.2 when you posted this issue (sorry for taking this long, btw). However, 0.5.3 has been released now. Does it fix your issue? If not, can I see an error message?

**Comment by slantview** [comment]
This did fix my error, sorry for the late reply.
