### ISSUE TITLE
Feature request: Allow providing files to release command.

### ISSUE THREAD

**Issue by c4milo** [aktau/github-release#15]
I would be convenient if the `upload` command could be integrated into the `release` command. Adding as well the ability to provide multiple file paths to the `--file` flag.

**Comment by mzmousa** [comment]
+1

**Comment by aktau** [comment]
I'm on the fence with this one. I realize it would make live easier, but I've already created a horrible command-line UI (I'd like to think I'd do it better if given another chance). Is there any more specific motivation for this other than "more convenient"? (Not that I think more conveniece bad, just that I'm trying to justify adding more options).

**Comment by c4milo** [comment]
Hey! This was a long time ago and no longer relevant. Feel free to close it. Thanks!

**Comment by titpetric** [comment]
@c4milo you opened it and you can close it. You can also add information about how it is solved for people who are looking at the same thing :)

**Comment by c4milo** [comment]
@titpetric, I ended up writing my own https://github.com/c4milo/github-release

**Comment by titpetric** [comment]
@c4milo Awesome, thanks. I might just use that one, for other reasons (makefile changelog/diff). :)

**Comment by aktau** [comment]
Neat. I like the user interface too.
