### ISSUE TITLE
Feature: progress indicator

### ISSUE THREAD

**Issue by jnweiger** [aktau/github-release#33]
I am uploading several hundred megabytes of assets to github. A simple progress bar or completion percentage would be great with the -v option and/or a new -p option.

**Comment by jnweiger** [comment]
Workaround using https://github.com/jnweiger/showspeed: run with showspeed --cmd github-release upload ....

**Comment by mloskot** [comment]
I'd be also thankful for considering this feature request. @jnweiger thanks for the `showspeed` workaround.

**Comment by aktau** [comment]
Hmm, a general progress indicator is (I think) a bit bloaty. However, you can use `-` to upload from stdin. To get an idea of the progress:

```bash
$ pv < myfile | github-release upload -f- ...
```

Is this good enough? Please let me know.

**Comment by zacharee** [comment]
@aktau that results in the following error:
```
error: could not upload, status code (400 Bad Request), msg: Bad Content-Length: , errors:
```
