### ISSUE TITLE
Feature: Create releases without tags

### ISSUE THREAD

**Issue by Careerbuilder2016** [aktau/github-release#37]
Here is my problem: I want to be able to create releases without tags just like you can create tags without releases. The problem is that GitHub provides an API for releases but not for tags. The only way to remove tags is to use the git cli commands in the repository. Example: 

```git ls-remote --tags origin | awk '/^(.*)(\s+)(.*[a-zA-Z0-9])$/ {print ":" $2}' | xargs git push origin```

Is there a way to add a release with an upload without a tag? Is there a way to delete the tags without doing it directly in the repository?

Maybe there is a way to pass an empty tag to the API?

**Comment by ailin-nemui** [comment]
those "releases" would be invisible Drafts, right?

**Comment by Careerbuilder2016** [comment]
Yes exactly. Here is an image of what it would look like:

![Image of Draft](http://i64.tinypic.com/zwm2au.png)

The problem is that, once the tag is deleted it becomes a draft, but it is still in the release API under releases. Still considered prerelease or release depending on what it was added as. But the tags cannot be removed through the API only through the git cli.

**Comment by ailin-nemui** [comment]
just use `--draft` instead of first pushing and then deleting the tag. keep in mind that drafts are only visible to yourself while logged in

**Comment by Careerbuilder2016** [comment]
Awesome, so when I specify --draft instead of prerelease or release it will automatically create a release without a tag?

I definitely did not notice this when doing ```github-release --help```

So even though they are only visible to me, I can get them from the Release API, correct?
This looks like the functionality I need.
