### ISSUE TITLE
Can't get info or edit releases older than github API single pagination

### ISSUE THREAD

**Issue by rberger** [aktau/github-release#41]
It looks like the `GithubGet` method gets just the latest set of releases and won't go thru the pagination. So if I want to get `info` or `edit` a release / tag that is older than what fits in one page retrieved by `GithubGet` it won't work.

My Go Fu isn't up to figuring out how to do it myself correctly.

**Comment by ThirteenAG** [comment]
I was having the same problem, so I had to use a workaround:
	RELEASE_LIST_URI    = "/repos/%s/%s/releases%s&per_page=100"
	RELEASE_LATEST_URI  = "/repos/%s/%s/releases/latest%s&per_page=100"
	TAGS_URI = "/repos/%s/%s/tags%s&per_page=100"

**Comment by aktau** [comment]
This has since been fixed (see https://github.com/aktau/github-release/commit/85aea45fc23f3479ee6d50476dc82b44d42cf9a1). Try the latest version (or compile from head to get rate-limited even less). Please let me know if it still doesn't work.
