### ISSUE TITLE
Force upload?

### ISSUE THREAD

**Issue by nathanleclaire** [aktau/github-release#43]
Is it possible to use `github-release` to force upload binaries if there are some already in place?

For some automation we're working on we have artifacts getting added on to an existing release, but sometimes corrupted ones get uploaded (due to a build fault) and we have to re-run the upload portion.  Right now we will manually remove them if such a thing happens.  Would there be interest in such a force upload feature and/or is it even possible through GH API?  Re-creating the entire release seems like overkill.

**Comment by mfonville** [comment]
@nathanleclaire I suggest you check out https://github.com/itchio/gothub/issues/1

**Comment by aktau** [comment]
In Addition to bringen available in gothub as @mfonville said, github-release 0.7.0 now also supports the --replace flag.

**Comment by nathanleclaire** [comment]
nice thanks for the followup @aktau
