### ISSUE TITLE
Uploading multiple files in one --file argument

### ISSUE THREAD

**Issue by mzmousa** [aktau/github-release#48]
Is it possible to upload multiple files at once with one `github-release upload` command, or must each file be uploaded in separate commands?
For example, I was wondering if this was possible, from the `README`:

```
# upload a file, for example the OSX/AMD64 binary of my gofinance app
$ github-release upload \
    --user aktau \
    --repo gofinance \
    --tag v0.1.0 \
    --name "gofinance-osx-amd64" \
    --file bin/darwin/amd64/gofinance
    --file file2
    --file file3
    --file file4
```

**Comment by alexblack** [comment]
+1

**Comment by emoshaya-cognito** [comment]
+1

**Comment by ostcar** [comment]
It would also be nice, if all files from a directory could be uploaded at once. For example with ```--file path/to/dir/*```

**Comment by aktau** [comment]
While this is possible to do, I'd tend towards keeping it a bit more UNIX. Is there any reason why you can't use the following, for example:

```
parallel github-release upload \
    --user aktau \
    --repo gofinance \
    --tag v0.1.0 \
    --name {} \
    --file {} ::: bin/darwin/amd64/gofinance file1 file2 file2
```

This uses GNU parallel, but xargs(1) can basically do the same thing. How does that sound?

@ostcar: You could do: `parallel github-release upload ... --name {} --file {} ::: path/to/dir/*`, no problem.

**Comment by samrocketman** [comment]
Here's how I did this with `xargs`.

```
ls -1 | xargs -n1 -P0 -I{} -- \
github-release upload --tag "${1}" --name '{}' --file '{}'
```

Also uploads in parallel.
