### ISSUE TITLE
Notification: AUR package for github-release created

### ISSUE THREAD

**Issue by fusion809** [aktau/github-release#51]
Hi,

I was referred to this program by @rsese, and I loved it so much I decided to create a package for the Arch User Repository (AUR) for it, [`github-release-bin`](https://aur.archlinux.org/packages/github-release-bin/). I am mentioning this because I thought it would be worthwhile mentioning this alternate means of installing this program on Arch Linux/derivative distributions (e.g., Manjaro Linux). Specifically Arch/Manjaro users with `yaourt` (which itself is an unofficial package for Arch Linux) installed can install this package with:

``` bash
yaourt -S github-release-bin
```

while Arch/Manjaro users with `pacaur` installed can install this package with;

``` bash
pacaur -S github-release-bin
```

Those with neither AUR helper installed can install `github-release-bin` with:

``` bash
curl -L https://aur.archlinux.org/cgit/aur.git/snapshot/github-release-bin.tar.gz | tar xz -C /tmp
cd /tmp/github-release-bin
makepkg -si --noconfirm
cd -
```

I can write a pull request to make these additions to the README, if you would like, but I know I'm not very good at being concise so I thought you might prefer to make the edit yourself. 

Thanks for your time and I hope this helps,
Brenton

**Comment by fusion809** [comment]
I created an extra AUR package, this one builds from source, [`github-release`](https://aur.archlinux.org/packages/github-releases).

**Comment by aktau** [comment]
Good to know. Thanks :).
