### ISSUE TITLE
error: github did not response with 200 OK but with 404 Not Found

### ISSUE THREAD

**Issue by emoshaya-cognito** [aktau/github-release#53]
I'm running the following:

```
export GITHUB_TOKEN=****************************

github-release info --user jenkins-cognito --repo cqrs
```

I keep getting the following error:

error: github did not response with 200 OK but with 404 Not Found

cqrs is a private repository in CognitoIQ Organisation. Could you please help?

**Comment by akaspin** [comment]
bump

**Comment by GabLeRoux** [comment]
@akaspin --user is not your actual user, it's the left part of the repo, ex, for the current repository, the command line would look like this:

```
github-release info --user aktau --repo github-release
```
I confirm the above command works. User is not your user, it's the user who owns the repository or the organization. This is definitely confusing indeed.

**Comment by emoshaya-cognito** [comment]
Thanks @GabLeRoux I can confirm your suggestion works.
