### ISSUE TITLE
github-release for new organisation.

### ISSUE THREAD

**Issue by vinaybheri** [aktau/github-release#57]
I am able to work with this github-release for my user account. 
But, I need to automate upload release and binary to separate development organization's repo. And, We can't create GITHUB_TOKEN key for organization in github.

So, is there a way to get it done?

**Comment by aktau** [comment]
I'm actually not sure, I've never worked with Github organisations in this way before. I do think some sort of token will be required, as github-release needs to have permissions. Perhaps you can create a reduced-privilege token?

**Comment by mfonville** [comment]
afaik releases and assets are always still done by a user, as member of organization, and not by the organization as entity

**Comment by aktau** [comment]
Seems like @mfonville has more experience with the GH API. I'd suggest creating a robot/fake user and add it to your organization, in order to perform changes.
