### ISSUE TITLE
Missing "--label" option in OSX binary

### ISSUE THREAD

**Issue by iwconfig** [aktau/github-release#60]
Well, as mentioned says. f10dc9e is not in the OSX binary release version 0.6.2.

**Comment by iwconfig** [comment]
`--version` also doesn't work

**Comment by aktau** [comment]
There was another similar report too. I'm not sure what went wrong here... I'm going to check the makefile. Do the latest binaries support the flag? They should... Please reopen if they don't

**Comment by iwconfig** [comment]
I have not fully tested it but `--label` is at least recognized and `--version` is working so i guess this issue can remain closed. :) great piece of software, gives a headache relief really. thanks!
