### ISSUE TITLE
github-release download: write to stdout or specify file location

### ISSUE THREAD

**Issue by kevinburke** [aktau/github-release#61]
I'd like to write

```
github-release download ... > $HOME/bin/filename
```

However the only documented option for github-release is to download to the current directory, to a file whose name matches the release filename.

**Comment by aktau** [comment]
Should be fixed in 0.6.3. Sorry I didn't see your PR, which would've also been fine. The solution I hacked up doesn't involve adding a new flag, and I would hope it does the right thing in 99% of all circumstances.
