### ISSUE TITLE
Getting error when trying to upload files to drafted release

### ISSUE THREAD

**Issue by kashishm** [aktau/github-release#66]
**Command**
```
github-release -v upload -u <user> -r <repo> -t "v0.0.3" -n <name> -f <file>
```

**Error**
```
uploading...
23:40:57.049 error: expected '200 OK' but received '404 Not Found' (url: https://api.github.com/repos/:owner/:repo/releases/tags/v0.0.3?access_token=******&per_page=100)
```

> Creating release works with the same access token
```
github-release release -u <user> -r <repo> --draft -t "v0.0.3" -d "Description" -n "name"
```

**Comment by aktau** [comment]
This is really really strange. I'm going to try and recreate this with a draft release.

**Comment by aktau** [comment]
Ah yes, the new method for finding the release of a tag (described here: https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name), commit 70ed556f1a4645bb80868084cf9cbec60824e5fd, does not support finding draft releases this way, I think. That sucks...

**Comment by aktau** [comment]
See if release 0.7.2 does it for you. If not, please reopen the issue.

**Comment by kashishm** [comment]
@aktau It is working now. Thanks for the fix.
