### ISSUE TITLE
Why using tar.bz2?

### ISSUE THREAD

**Issue by samrocketman** [aktau/github-release#69]
Other go projects directly publish their go binaries.  It simplifies downloading it via script.  If compression is the concern then why use `.tar.bz2` with a directory structure inside?  i.e. `bin/linux/amd64/github-release`.

One could simply use `bzip2` to create a `github-release.bz2` since there is only a single file.  Tape archive (tar) command is typically used when there's more than one file which needs to be archived and compressed.

**Comment by samrocketman** [comment]
For what it's worth here's how I get around the problem.

    tar --xform='s#^.+/##x' -xjf ../linux-amd64-github-release.tar.bz2

**Comment by aktau** [comment]
Hi Sam,

You're right, it's pretty poor form. The compression is useful since the binary really does compress a lot.

I've added a commit to fix it (generate direct bzip2'ed files). If this is good for you, I'll create a new release and upload those files. Please let me know.

**Comment by samrocketman** [comment]
Direct `bzip2` files are good with me :smiley_cat: .  `tar.bzip2` was only a minor inconvenience since I had a workaround.  Thanks for addressing this.
