### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by chitin** [aktau/github-release#70]
../../../go/bin/src/github.com/aktau/github-release/cmd.go:96: enc.SetIndent undefined (type *json.Encoder has no field or method SetIndent)

**Comment by aktau** [comment]
It seems like you're using an version of Go older than v1.7, when json.Encoder.SetIndent was introduced. See https://github.com/golang/dep/issues/230.

You can still pull from older commits (before SetIndent was introduced) or download the precompiled binary assets from the releases page.

There's no formal support level for which version of Go github-release will compile with. If enough users say it is a big problem to support only 1.7+, then I'll think about coding some shims or outright removing the formatting functionality.
